
import React from 'react';
import { ShieldCheck, AlertTriangle, CheckCircle } from 'lucide-react';
import { Project } from '../types';

interface ReportProps {
  project: Project;
  orderId: string;
  score: number;
}

export const PlagiarismReport: React.FC<ReportProps> = ({ project, orderId, score }) => {
  const isSafe = score < 20;
  const colorClass = isSafe ? 'text-green-600 border-green-200 bg-green-50' : (score < 40 ? 'text-yellow-600 border-yellow-200 bg-yellow-50' : 'text-red-600 border-red-200 bg-red-50');

  return (
    <div className="bg-white w-full h-full p-12 max-w-[210mm] mx-auto shadow-2xl overflow-y-auto print:shadow-none">
      {/* Header */}
      <div className="flex justify-between items-end border-b-2 border-slate-900 pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight">Pygenicarc<span className="text-orange-600">Tech</span></h1>
          <p className="text-xs text-slate-500 uppercase tracking-widest mt-1">Authenticity Verification Report</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold text-slate-900">Report ID: <span className="font-mono">{orderId}-REP</span></p>
          <p className="text-xs text-slate-500">Date: {new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Summary Score */}
      <div className="mb-12">
        <h2 className="text-lg font-bold text-slate-900 mb-4">Originality Summary</h2>
        <div className={`flex items-center p-6 rounded-xl border-2 ${colorClass}`}>
          <div className="flex-1">
            <p className="text-sm font-semibold uppercase tracking-wide opacity-80">Similarity Index</p>
            <p className="text-5xl font-black mt-2">{score}%</p>
          </div>
          <div className="text-right">
            {isSafe ? (
              <div className="flex items-center">
                <ShieldCheck className="w-12 h-12 mr-3" />
                <span className="text-lg font-bold">Passed</span>
              </div>
            ) : (
              <div className="flex items-center">
                <AlertTriangle className="w-12 h-12 mr-3" />
                <span className="text-lg font-bold">Attention Needed</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Project Details */}
      <div className="mb-12">
        <h2 className="text-lg font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2">Project Details</h2>
        <div className="grid grid-cols-2 gap-y-4 text-sm">
          <div className="text-slate-500">Project Title:</div>
          <div className="font-bold text-slate-900">{project.title}</div>
          
          <div className="text-slate-500">Department:</div>
          <div className="font-medium text-slate-900">{project.department}</div>
          
          <div className="text-slate-500">Submission Type:</div>
          <div className="font-medium text-slate-900">Source Code & Documentation</div>
          
          <div className="text-slate-500">Word Count:</div>
          <div className="font-medium text-slate-900">~2,500 Words</div>
        </div>
      </div>

      {/* Database Matches */}
      <div className="mb-12">
        <h2 className="text-lg font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2">Primary Sources</h2>
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-slate-500 uppercase bg-slate-50">
            <tr>
              <th className="px-4 py-2">Source</th>
              <th className="px-4 py-2">Similarity</th>
              <th className="px-4 py-2">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            <tr>
              <td className="px-4 py-3">Internet Source (Github)</td>
              <td className="px-4 py-3 font-mono">2%</td>
              <td className="px-4 py-3 text-green-600"><CheckCircle className="w-4 h-4 inline mr-1"/> Valid</td>
            </tr>
            <tr>
              <td className="px-4 py-3">Student Papers (Repository)</td>
              <td className="px-4 py-3 font-mono">1%</td>
              <td className="px-4 py-3 text-green-600"><CheckCircle className="w-4 h-4 inline mr-1"/> Valid</td>
            </tr>
             <tr>
              <td className="px-4 py-3">IEEE Journals</td>
              <td className="px-4 py-3 font-mono">3%</td>
              <td className="px-4 py-3 text-green-600"><CheckCircle className="w-4 h-4 inline mr-1"/> Valid</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="mt-auto pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
        <p>This report is system generated by Pygenicarc Technologies Algorithm v2.4.</p>
        <p>Verified on {new Date().toLocaleString()}</p>
      </div>
    </div>
  );
};
